# Generated by Django 3.0.5 on 2020-05-27 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='state',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
